apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: connections-service
  name: connections-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connections-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: connections-service
    spec:
      containers:
        - image: enkhalifapro/connections-service:latest
          imagePullPolicy: IfNotPresent
          name: connections-service
          resources:
            requests:
              cpu: 50m
              memory: 256Mi