apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: persons-service
  name: persons-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persons-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: persons-service
    spec:
      containers:
        - image: enkhalifapro/persons-service:latest
          imagePullPolicy: IfNotPresent
          name: persons-service
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: persons-service
  name: persons-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    service: persons-service
  type: NodePort
---